#\u81EA\u5B9A\u4E49\u9879\u76EE\u7AEF\u53E3
server:
  port: 8888
  servlet:
    session:
      timeout: 30
  tomcat:
    uri-encoding: utf-8

#mysql\u914D\u7F6E
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/demo
#    username: root
#    password: root
#    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: my-demo-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.30.130:8848
      config:
        server-addr: 192.168.30.130:8848
mybatis-plus:
  #\u914D\u7F6Emapper\u6620\u5C04\u6587\u4EF6
  #  mapper-locations: classpath:/mapper/**.xml
  configuration:
    #\u6253\u5370\u5B8C\u6574\u5E26\u53C2\u6570SQL\u8BED\u53E5
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#\u914D\u7F6EpageHelper
pagehelper:
  dialect: mysql